[theme]
primaryColor = "#3498DB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#ECF0F1"
textColor = "#2C3E50"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
port = 8501
